import { Router, type IRouter } from "express";
import healthRouter from "./system/health";
import authRouter from "./auth/auth";
import usersRouter from "./auth/users";
import backupRouter from "./system/backup";
import reservationsRouter from "./booking/reservations";
import settingsRouter from "./system/settings";
import statsRouter from "./system/stats";
import facilitiesRouter from "./booking/facilities";
import instructorsRouter from "./booking/instructors";
import announcementsRouter from "./support/announcements";
import walletRouter from "./finance/wallet";
import topupRouter from "./finance/topup";
import packagesRouter from "./membership/packages";
import packageCategoriesRouter from "./membership/categories";
import couponsRouter from "./membership/coupons";
import reviewsRouter from "./support/reviews";
import chatRouter from "./support/chat";
import checkinRouter from "./booking/checkin";
import notificationsRouter from "./support/notifications";
import productsRouter from "./shop/products";
import ordersRouter from "./shop/orders";
import aiChatRouter from "./support/aiChat";
import themeRouter from "./system/theme";
import devSupportRouter from "./support/devSupport";
import attendanceRouter from "./staff/attendance";
import branchesRouter from "./system/branches";
import leaveRouter from "./staff/leave";
import tasksRouter from "./staff/tasks";
import auditLogsRouter from "./system/auditLogs";
import updateRouter from "./system/update";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/backup", backupRouter);
router.use("/reservations", reservationsRouter);
router.use("/settings", settingsRouter);
router.use("/stats", statsRouter);
router.use("/facilities", facilitiesRouter);
router.use("/instructors", instructorsRouter);
router.use("/announcements", announcementsRouter);
router.use("/wallet", walletRouter);
router.use("/topup", topupRouter);
router.use("/packages", packagesRouter);
router.use("/package-categories", packageCategoriesRouter);
router.use("/coupons", couponsRouter);
router.use("/reviews", reviewsRouter);
router.use("/chat", chatRouter);
router.use("/checkin", checkinRouter);
router.use("/notifications", notificationsRouter);
router.use("/products", productsRouter);
router.use("/orders", ordersRouter);
router.use("/ai-chat", aiChatRouter);
router.use("/theme", themeRouter);
router.use("/dev-support", devSupportRouter);
router.use("/attendance", attendanceRouter);
router.use("/branches", branchesRouter);
router.use("/leave", leaveRouter);
router.use("/tasks", tasksRouter);
router.use("/audit-logs", auditLogsRouter);
router.use("/update", updateRouter);

export default router;
